create table "user_entity" (
     user_id    int8         generated by default as identity,
     username   varchar(255) not null,
     password   varchar(255) not null,
     role       varchar(40)  not null,
     primary key (user_id)
);

